config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :sugestoes
  resources :vendas
  resources :livros
  resources :funcionarios
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  root 'sessions#new'
  
get "/buscar" => "livros#buscar"

post "/resultado" => "livros#resultado"

end

app/models/venda.rb
class Venda < ActiveRecord::Base
	validates :valor, numericality: {greater_than: 0}
end

app/controllers/vendas_controller.rb
class VendasController < ApplicationController
  before_action :set_venda, only: [:show, :edit, :update, :destroy]

  # GET /vendas
  # GET /vendas.json
  def index
    @vendas = Venda.all
  end

  # GET /vendas/1
  # GET /vendas/1.json
  def show
  end

  # GET /vendas/new
  def new
    @venda = Venda.new
  end

  # GET /vendas/1/edit
  def edit
  end

  # POST /vendas
  # POST /vendas.json
  def create
     @funcionarios = Funcionario.all()
     @livros = Livro.all()
     @venda = Venda.new(venda_params)
     String nome_livro = venda_params[:livro]
    salvou =false
    String nome = venda_params[:funcionario]
    @funcionarios.each{|funcionario|
      print " \nFUNCIONARIO: " + funcionario.nome
      if (funcionario.nome.eql? nome)
        print "\nAchei ele: " + funcionario.nome + " e " + nome
        @livros.each{|livro|
          if (livro.titulo.eql? nome_livro)
            print "\n Achei o livro: " + livro.titulo + " e " + nome_livro
            @venda.save
            salvou = true
          end
        }
      end
    }
    respond_to do |format|
      if salvou
        format.html { redirect_to @venda, notice: 'Venda concluida com sucesso!'}
        format.json { render :show, status: :created, location: @venda }
      else
        format.html { redirect_to @venda, notice: 'Erro na venda, livro ou funcionario não encontrado' }
        format.json { render json: @venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendas/1
  # PATCH/PUT /vendas/1.json
  def update
    respond_to do |format|
      if @venda.update(venda_params)
        format.html { redirect_to @venda, notice: 'Venda was successfully updated.' }
        format.json { render :show, status: :ok, location: @venda }
      else
        format.html { render :edit }
        format.json { render json: @venda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendas/1
  # DELETE /vendas/1.json
  def destroy
    @venda.destroy
    respond_to do |format|
      format.html { redirect_to vendas_url, notice: 'Venda was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_venda
      @venda = Venda.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def venda_params
      params.require(:venda).permit(:funcionario, :livro, :valor)
    end
  end

app/helpers/vendas_helper.rb
module VendasHelper
end

app/views/vendas/_form.html.erb
<%= form_for(@venda) do |f| %>
  <% if @venda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@venda.errors.count, "error") %> prohibited this venda from being saved:</h2>

      <ul>
      <% @venda.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :funcionario %><br>
    <%= f.text_field :funcionario %>
  </div>
  <div class="field">
    <%= f.label :livro %><br>
    <%= f.text_field :livro %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.text_field :valor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendas/edit.html.erb
<h1>Editar Venda</h1>

<%= render 'form' %>

<%= link_to 'Show', @venda %> |
<%= link_to 'Back', vendas_path %>

app/views/vendas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vendas</h1>

<table border="1" cellpadding="5px" cellspacing="5px">
  <thead>
    <tr>
        <th> Funcionário </th>
        <th> Título </th>
        <th> Valor </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendas.each do |venda| %>
      <tr>
        <td><%= venda.funcionario %></td>
        <td><%= venda.livro %></td>
        <td><%= venda.valor %></td>
        <td><%= link_to 'Mostrar', venda %></td>
        <td><%= link_to 'Editar', edit_venda_path(venda) %></td>
        <td><%= link_to 'Excluir', venda, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<strong><i><%= link_to '<< Nova Venda >>', new_venda_path %></i></strong>

app/views/vendas/new.html.erb
<h1>Nova Venda</h1>

<%= render 'form' %>

<strong><%= link_to '<< Back', vendas_path %></strong>

app/views/vendas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Funcionario:</strong>
  <%= @venda.funcionario %>
</p>

<p>
  <strong>Livro:</strong>
  <%= @venda.livro %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @venda.valor %>
</p>

<%= link_to 'Edit', edit_venda_path(@venda) %> |
<%= link_to 'Back', vendas_path %>