config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :sugestoes
  resources :vendas
  resources :livros
  resources :funcionarios
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  root 'sessions#new'
  
get "/buscar" => "livros#buscar"

post "/resultado" => "livros#resultado"

end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
	validates :nome, presence:true
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  before_action :authorize, except: [:index, :show]

  # GET /funcionarios
  # GET /funcionarios.json
  def index
    @funcionarios = Funcionario.all
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
  end

  # GET /funcionarios/new
  def new
    @funcionario = Funcionario.new
  end

  # GET /funcionarios/1/edit
  def edit
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(funcionario_params)

    respond_to do |format|
      if @funcionario.save
        format.html { render '/funcionarios/show', :params => @funcionario, notice: 'Funcionario cadastrado com sucesso!' }
        format.json { render :show, status: :created, location: @funcionario }
      else
        format.html { render :new }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /funcionarios/1
  # PATCH/PUT /funcionarios/1.json
  def update
    respond_to do |format|
      if @funcionario.update(funcionario_params)
        format.html { redirect_to @funcionario, notice: 'Cadastro alterado com sucesso!' }
        format.json { render :show, status: :ok, location: @funcionario }
      else
        format.html { render :edit }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario = Funcionario.find(params[:id]) 
    @funcionario.destroy
    @funcionarios = Funcionario.all 
    respond_to do |format|
      format.html { render '/funcionarios/index', :params => @funcionarios, notice: 'Cadastro excluído!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_funcionario
      @funcionario = Funcionario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def funcionario_params
      params.require(:funcionario).permit(:nome, :cpf, :email, :senha)
    end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/_form.html.erb
<%= form_for(@funcionario) do |f| %>
  <% if @funcionario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
      <% @funcionario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br>
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :senha %><br>
    <%= f.text_field :senha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/funcionarios/edit.html.erb
<h1>Editar Funcionário</h1>

<%= render 'form' %>

<%= link_to 'Show', @funcionario %> |
<%= link_to 'Back', funcionarios_path %>

app/views/funcionarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cadastro de Funcionários</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @funcionarios.each do |funcionario| %>
      <tr>
        <p><td><%= funcionario.nome %></td></p>
        <!--<td><%= funcionario.cpf %></td>
        <td><%= funcionario.email %></td>
        <td><%= funcionario.senha %></td>
        <td><%= link_to 'Mostrar', funcionario %></td>-->
      </tr>
  </tbody>

      <tr>
        <td><%= link_to 'Excluir', funcionario, method: :delete, data: { confirm: 'Deseja excluir o cadastro?' } %>
        </td>
      </tr>

    <% end %>
</table>

<br>

<strong><i><%= link_to '<< Novo funcionário >>', new_funcionario_path %></i></strong>

app/views/funcionarios/new.html.erb
<h1>Cadastro de Funcionários</h1>

<%= render 'form' %>

<strong><%= link_to '<< Back', funcionarios_path %></strong>

app/views/funcionarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @funcionario.nome %>
</p>
<p>
  <strong>Cpf:</strong>
  <%= @funcionario.cpf %>
</p>

<p>
  <strong>Email:</strong>
  <%= @funcionario.email %>
</p>

<p>
  <strong>Senha:</strong>
  <%= @funcionario.senha %>
</p>
<%= link_to 'Back', funcionarios_path %>