config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :sugestoes
  resources :vendas
  resources :livros
  resources :funcionarios
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  root 'sessions#new'
  
get "/buscar" => "livros#buscar"

post "/resultado" => "livros#resultado"

end

app/models/livro.rb
class Livro < ActiveRecord::Base

	def self.search(query)
		where("titulo LIKE :q", :q => "%#{query}%")
	end
end
 

app/controllers/livros_controller.rb
class LivrosController < ApplicationController
  before_action :authorize, except: [:index, :show, :resultado, :buscar]
  respond_to :html, :xml, :json

  # GET /livros
  # GET /livros.json
  def index
    @livros = Livro.all
  end

  def buscar
  end

  def resultado
    @livros = Livro.search(params[:query])
    respond_with @livros
  end

  # GET /livros/1
  # GET /livros/1.json
  def show
  end

  # GET /livros/new
  def new
    @livro = Livro.new
  end

  # GET /livros/1/edit
  def edit
    @livro = Livro.new(livro_params)
    render 'livros/edit', :params =>@livro
  end

  # POST /livros
  # POST /livros.json
  def create
    @livro = Livro.new(livro_params)

    respond_to do |format|
      if @livro.save
        format.html { render '/livros/show', :params => @livro, notice: 'Livro cadastrado com sucesso!' }
        format.json { render :show, status: :created, location: @livro }
      else
        format.html { render :new }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /livros/1
  # PATCH/PUT /livros/1.json
  def update
    respond_to do |format|
      if @livro.update(livro_params)
        format.html { redirect_to @livro, notice: 'Cadastro alterado com sucesso!' }
        format.json { render :show, status: :ok, location: @livro }
      else
        format.html { render :edit }
        format.json { render json: @livro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /livros/1
  # DELETE /livros/1.json
  def destroy
    @livro = Livro.find(params[:id])
    @livro.destroy
    @livros = Livro.all
    respond_to do |format|
      format.html { render '/livros/index', :params => @livros, notice: 'Cadastro excluido com sucesso!' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_livro
      @livro = Livro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def livro_params
      params.require(:livro).permit(:titulo, :autor, :genero, :preco)
    end
end

app/helpers/livros_helper.rb
module LivrosHelper
end

app/views/livros/_form.html.erb
<%= form_for(@livro) do |f| %>
  <% if @livro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@livro.errors.count, "error") %> prohibited this livro from being saved:</h2>

      <ul>
      <% @livro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo %>
  </div>
  <div class="field">
    <%= f.label :autor %><br>
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :genero %><br>
    <%= f.select :genero, ['Ação','Aventura', 'Comédia', 'Contos', 'Crônicas', 'Didáticos','Drama', 'Fantasia','Ficção Científica', 'Infanto-Juvenil', 'Poesia', 'Romance','Terror']%> 
  </div>
  <div class="field">
    <%= f.label :preco %><br>
    <%= f.text_field :preco %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/livros/buscar.html.erb
<%= form_tag resultado_path, :method => "post" do %>
<%= text_field_tag :query, params[:query]%>
<%= submit_tag "Procurar", :titulo => nil %>
<% end%>

app/views/livros/edit.html.erb
<h1>Editar Livro</h1>

<%= render 'form' %>

<%= link_to 'Show', @livro %> |
<%= link_to 'Back', livros_path %>

app/views/livros/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Livros</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @livros.each do |livro| %>
      <tr>
        <tr><td><strong><u><%= livro.titulo %></u></strong></td></tr>
      
        <tr><td><%= livro.autor %></td></tr>
     
        <tr><td><%= livro.genero %></td></tr>
   
        <tr><td><%= livro.preco %></td></tr>
      </tr>
  </tbody>

      <tr>
        <td><%= link_to 'Excluir', livro, method: :delete, data: { confirm: 'Deseja excluir o cadastro?' } %></td>
        
      </tr>
    <% end %>

</table>

<br>

<strong><i><%= link_to '<< Novo Livro >>', new_livro_path %></i></strong>

app/views/livros/new.html.erb
<h1>Novo Livro</h1>

<%= render 'form' %>

<strong><%= link_to '<< Back', livros_path %></strong>

app/views/livros/resultado.html.erb
<h3> Resultado da pesquisa </h3>

<tbody>
	<% @livros.each do |livro| %>
	<tr>
		<p>  
		<strong>Título:</strong> 
		<%= livro.titulo %>
		</p><td>   
		</td>
		<td>  
		<strong>Autor:</strong> 
		<%= livro.autor %>
		</td><td>   
		</td>
		<td>  
		<strong>Gênero:</strong> 
		<%= livro.genero %>
		</td>
		<td></td>
		<td>  
		<strong>Preço:</strong> 
		<%= livro.preco %>
		</td>
	</tr>
<br></br>
	<% end %>
</tbody>
</br>
<td><%= link_to "Nova Busca", buscar_path %></td>

app/views/livros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Título:</strong>
  <%= @livro.titulo %>
</p>

<p>
  <strong>Autor:</strong>
  <%= @livro.autor %>
</p>

<p>
  <strong>Gênero:</strong>
  <%= @livro.genero %>
</p>

<p>
  <strong>Preço:</strong>
  <%= @livro.preco %>
</p>

<%= link_to 'Voltar', livros_path %>