config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'users/new'

  resources :sugestoes
  resources :vendas
  resources :livros
  resources :funcionarios
  resources :users
  get    'sign_in'   => 'sessions#new'
  post   'sign_in'   => 'sessions#create'
  delete 'sign_out'  => 'sessions#destroy'
  root 'sessions#new'
  
get "/buscar" => "livros#buscar"

post "/resultado" => "livros#resultado"

end

app/views/layouts/_header.html.erb
<li><%= link_to "Settings",
edit_user_path(current_user) %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EP3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<body background="http://www.treta.com.br/wp-content/uploads/2013/12/20160602-o-coffee-bookshop-facebook.jpg">
<header>
    <div>
      <nav>
        <ul>
        </ul>
      </nav>
    </div>
  </header>
<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      
	      <a class="navbar-brand" href="/">Menu</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li><a href="/livros">Livros </a></li>
	        <li><a href="/funcionarios">Funcionários</a></li>
	        <li><a href="vendas">Vendas</a></li>
	       	<li><a href="buscar">Buscar</a></li>
	      </ul>
	      <!-- <form class="navbar-form navbar-left" role="search">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="buscar">
	        </div> 
	        <button type="submit" class="btn btn-default">Buscar</button> 
	      </form> -->
	      <ul class="nav navbar-nav navbar-right">
	          <% if logged_in? %>
	            <li><%= link_to "Sair", sign_out_path, method: "delete" %></li>
	          <% else %>
	            <li><%= link_to "Entrar", root_path %></li>
	          <% end %>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
<%= yield %>

</body>

</body>
</html>